apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secret-checker

bases:
 - ../base

secretGenerator:
  - name: secret-checker
    kvSources:
      - name: kustomize-sops
        pluginType: go
        args:
          - secret-value

